/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountsOut {
    /// Accounts are the ledger accounts in scope with their balances.
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<models::AccountView>>,
    /// Scope is the scope actually served: \"org\" or \"house\".
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    /// Tenant is the org whose accounts these are (empty for the house scope's own rows).
    #[serde(rename = "tenant", skip_serializing_if = "Option::is_none")]
    pub tenant: Option<String>,
}

impl AccountsOut {
    pub fn new() -> AccountsOut {
        AccountsOut {
            accounts: None,
            scope: None,
            tenant: None,
        }
    }
}

