/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminBonusDirectory {
    /// Referrals is every referral in the ledger, both orgs exposed.
    #[serde(rename = "referrals", skip_serializing_if = "Option::is_none")]
    pub referrals: Option<Vec<models::AdminReferralView>>,
    /// Summary is the fleet tally across those referrals.
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Box<models::AdminSummary>>,
}

impl AdminBonusDirectory {
    pub fn new() -> AdminBonusDirectory {
        AdminBonusDirectory {
            referrals: None,
            summary: None,
        }
    }
}

