/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminEnablementBoard {
    /// Items is every item an operator has set a state on. An item nobody has touched is absent: it is generally available by default.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::AdminEnablementItem>>,
}

impl AdminEnablementBoard {
    pub fn new() -> AdminEnablementBoard {
        AdminEnablementBoard {
            items: None,
        }
    }
}

