/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentsResourceUsage : All fields are null — this store meters no CPU/memory/storage/cost; the console renders \"—\". 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentsResourceUsage {
    #[serde(rename = "cpuVcpuHours", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cpu_vcpu_hours: Option<Option<f64>>,
    #[serde(rename = "memGbHours", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mem_gb_hours: Option<Option<f64>>,
    #[serde(rename = "storageIoBytes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage_io_bytes: Option<Option<f64>>,
    #[serde(rename = "costCents", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cost_cents: Option<Option<f64>>,
}

impl AgentsResourceUsage {
    /// All fields are null — this store meters no CPU/memory/storage/cost; the console renders \"—\". 
    pub fn new() -> AgentsResourceUsage {
        AgentsResourceUsage {
            cpu_vcpu_hours: None,
            mem_gb_hours: None,
            storage_io_bytes: None,
            cost_cents: None,
        }
    }
}

