/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsReport {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<uuid::Uuid>,
    #[serde(rename = "websiteId", skip_serializing_if = "Option::is_none")]
    pub website_id: Option<uuid::Uuid>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl AnalyticsReport {
    pub fn new() -> AnalyticsReport {
        AnalyticsReport {
            id: None,
            user_id: None,
            website_id: None,
            r#type: None,
            name: None,
            description: None,
            parameters: None,
            created_at: None,
            updated_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "funnel")]
    Funnel,
    #[serde(rename = "insights")]
    Insights,
    #[serde(rename = "retention")]
    Retention,
    #[serde(rename = "utm")]
    Utm,
    #[serde(rename = "goals")]
    Goals,
    #[serde(rename = "journey")]
    Journey,
    #[serde(rename = "revenue")]
    Revenue,
    #[serde(rename = "attribution")]
    Attribution,
}

impl Default for Type {
    fn default() -> Type {
        Self::Funnel
    }
}

