/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthoredPluginList {
    /// Plugins is every plugin this org built, newest first, each carrying the TypeScript as authored. The bundled artifact is never rendered.
    #[serde(rename = "plugins", skip_serializing_if = "Option::is_none")]
    pub plugins: Option<Vec<models::AuthoredPlugin>>,
}

impl AuthoredPluginList {
    pub fn new() -> AuthoredPluginList {
        AuthoredPluginList {
            plugins: None,
        }
    }
}

