/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BotList {
    /// Bots is one row per kind=bot machine, each joined with its agent binding when it has one.
    #[serde(rename = "bots", skip_serializing_if = "Option::is_none")]
    pub bots: Option<Vec<models::BotView>>,
}

impl BotList {
    pub fn new() -> BotList {
        BotList {
            bots: None,
        }
    }
}

