/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Catalog {
    #[serde(rename = "connectorCount", skip_serializing_if = "Option::is_none")]
    pub connector_count: Option<i32>,
    #[serde(rename = "connectors", skip_serializing_if = "Option::is_none")]
    pub connectors: Option<Vec<models::ConnectorMetadata>>,
}

impl Catalog {
    pub fn new() -> Catalog {
        Catalog {
            connector_count: None,
            connectors: None,
        }
    }
}

