/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudBookResponse {
    /// Posted is true when this call wrote the voucher, false when the same scan had already booked and nothing was written.
    #[serde(rename = "posted", skip_serializing_if = "Option::is_none")]
    pub posted: Option<bool>,
    /// ScanID echoes the scan that was booked.
    #[serde(rename = "scanId", skip_serializing_if = "Option::is_none")]
    pub scan_id: Option<String>,
}

impl CloudBookResponse {
    pub fn new() -> CloudBookResponse {
        CloudBookResponse {
            posted: None,
            scan_id: None,
        }
    }
}

