/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudCompanyReq {
    /// ARR is annual recurring revenue in minor units (cents) of Currency.
    #[serde(rename = "arr", skip_serializing_if = "Option::is_none")]
    pub arr: Option<i32>,
    /// City is the head-office city.
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// Country is the head-office country.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Currency is the ISO code ARR is denominated in; empty defaults to USD.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// DomainName is the company's primary domain, e.g. \"acme.com\".
    #[serde(rename = "domainName", skip_serializing_if = "Option::is_none")]
    pub domain_name: Option<String>,
    /// Employees is the headcount.
    #[serde(rename = "employees", skip_serializing_if = "Option::is_none")]
    pub employees: Option<i32>,
    /// ID names the company to update and comes from the path. A create ignores it: the server mints the id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// ICP marks the company as an ideal-customer-profile fit.
    #[serde(rename = "idealCustomerProfile", skip_serializing_if = "Option::is_none")]
    pub ideal_customer_profile: Option<bool>,
    /// Linkedin is the company's LinkedIn URL.
    #[serde(rename = "linkedinLink", skip_serializing_if = "Option::is_none")]
    pub linkedin_link: Option<String>,
    /// Name is the company name. Required.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// XLink is the company's X (Twitter) URL.
    #[serde(rename = "xLink", skip_serializing_if = "Option::is_none")]
    pub x_link: Option<String>,
}

impl CloudCompanyReq {
    pub fn new() -> CloudCompanyReq {
        CloudCompanyReq {
            arr: None,
            city: None,
            country: None,
            currency: None,
            domain_name: None,
            employees: None,
            id: None,
            ideal_customer_profile: None,
            linkedin_link: None,
            name: None,
            x_link: None,
        }
    }
}

