/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudSweepData {
    /// AccruedCents is the amount moved into the reserve fund.
    #[serde(rename = "accruedCents", skip_serializing_if = "Option::is_none")]
    pub accrued_cents: Option<i32>,
    /// Created is false when this period had already been swept — the accrual is idempotent.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<bool>,
    /// Period is the period actually accrued.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    /// ReserveCents is the fund balance after the accrual.
    #[serde(rename = "reserveCents", skip_serializing_if = "Option::is_none")]
    pub reserve_cents: Option<i32>,
    /// RevenueCents is the revenue the share was computed from.
    #[serde(rename = "revenueCents", skip_serializing_if = "Option::is_none")]
    pub revenue_cents: Option<i32>,
}

impl CloudSweepData {
    pub fn new() -> CloudSweepData {
        CloudSweepData {
            accrued_cents: None,
            created: None,
            period: None,
            reserve_cents: None,
            revenue_cents: None,
        }
    }
}

