/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudAnchorStatus {
    #[serde(rename = "chainId", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<i32>,
    #[serde(rename = "contract", skip_serializing_if = "Option::is_none")]
    pub contract: Option<String>,
    /// 0x… root of the journal as it stands now
    #[serde(rename = "currentRoot", skip_serializing_if = "Option::is_none")]
    pub current_root: Option<String>,
    #[serde(rename = "entryCount", skip_serializing_if = "Option::is_none")]
    pub entry_count: Option<i32>,
    #[serde(rename = "lastAt", skip_serializing_if = "Option::is_none")]
    pub last_at: Option<i32>,
    #[serde(rename = "lastBlock", skip_serializing_if = "Option::is_none")]
    pub last_block: Option<i32>,
    /// The last committed on-chain anchor (nil-fields until the first successful submit).
    #[serde(rename = "lastRoot", skip_serializing_if = "Option::is_none")]
    pub last_root: Option<String>,
    #[serde(rename = "lastTxHash", skip_serializing_if = "Option::is_none")]
    pub last_tx_hash: Option<String>,
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(rename = "rpcConfigured", skip_serializing_if = "Option::is_none")]
    pub rpc_configured: Option<bool>,
    #[serde(rename = "signerConfigured", skip_serializing_if = "Option::is_none")]
    pub signer_configured: Option<bool>,
    /// pending | anchored | error
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// true when the last anchored root == the current root
    #[serde(rename = "synced", skip_serializing_if = "Option::is_none")]
    pub synced: Option<bool>,
}

impl CloudAnchorStatus {
    pub fn new() -> CloudAnchorStatus {
        CloudAnchorStatus {
            chain_id: None,
            contract: None,
            current_root: None,
            entry_count: None,
            last_at: None,
            last_block: None,
            last_root: None,
            last_tx_hash: None,
            note: None,
            rpc_configured: None,
            signer_configured: None,
            status: None,
            synced: None,
        }
    }
}

