/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudCaptableRound {
    /// CloseDate is the ISO date the round closed, once it has.
    #[serde(rename = "closeDate", skip_serializing_if = "Option::is_none")]
    pub close_date: Option<String>,
    /// CreatedAt is when the round was recorded, in unix milliseconds.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i32>,
    /// ID is the round id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name is the round name, e.g. \"Series A\".
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// PreMoneyValuation is the pre-money valuation, for a priced round.
    #[serde(rename = "preMoneyValuation", skip_serializing_if = "Option::is_none")]
    pub pre_money_valuation: Option<f64>,
    /// PricePerShare is the price per share, for a priced round.
    #[serde(rename = "pricePerShare", skip_serializing_if = "Option::is_none")]
    pub price_per_share: Option<f64>,
    /// RaisedAmount is how much has been invested so far.
    #[serde(rename = "raisedAmount", skip_serializing_if = "Option::is_none")]
    pub raised_amount: Option<f64>,
    /// RoundType is PRICED, SAFE or CONVERTIBLE_NOTE.
    #[serde(rename = "roundType", skip_serializing_if = "Option::is_none")]
    pub round_type: Option<String>,
    /// ShareClassID is the class a priced round issues into.
    #[serde(rename = "shareClassId", skip_serializing_if = "Option::is_none")]
    pub share_class_id: Option<String>,
    /// Status is OPEN or CLOSED.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// TargetAmount is how much the round set out to raise.
    #[serde(rename = "targetAmount", skip_serializing_if = "Option::is_none")]
    pub target_amount: Option<f64>,
}

impl CloudCaptableRound {
    pub fn new() -> CloudCaptableRound {
        CloudCaptableRound {
            close_date: None,
            created_at: None,
            id: None,
            name: None,
            pre_money_valuation: None,
            price_per_share: None,
            raised_amount: None,
            round_type: None,
            share_class_id: None,
            status: None,
            target_amount: None,
        }
    }
}

