/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudWebOverview {
    /// Available is false when the product-event table could not be read — the lens is reported missing rather than as zeros that look like real traffic.
    #[serde(rename = "available", skip_serializing_if = "Option::is_none")]
    pub available: Option<bool>,
    /// Pageviews is how many $pageview events landed in the window.
    #[serde(rename = "pageviews", skip_serializing_if = "Option::is_none")]
    pub pageviews: Option<i32>,
    /// Reason says why the lens is unavailable. Omitted when it is available.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Sessions is how many distinct visits they span.
    #[serde(rename = "sessions", skip_serializing_if = "Option::is_none")]
    pub sessions: Option<i32>,
    /// Source is the warehouse table the lens read.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// Visitors is how many distinct people those pageviews came from.
    #[serde(rename = "visitors", skip_serializing_if = "Option::is_none")]
    pub visitors: Option<i32>,
}

impl CloudWebOverview {
    pub fn new() -> CloudWebOverview {
        CloudWebOverview {
            available: None,
            pageviews: None,
            reason: None,
            sessions: None,
            source: None,
            visitors: None,
        }
    }
}

