/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudCommerceOverview {
    /// AOV is average order value — Revenue/Orders, rounded to two places. Zero when there were no orders.
    #[serde(rename = "aov", skip_serializing_if = "Option::is_none")]
    pub aov: Option<f64>,
    /// Available is false when the product-event table could not be read — the lens is reported missing rather than as zeros that look like no sales.
    #[serde(rename = "available", skip_serializing_if = "Option::is_none")]
    pub available: Option<bool>,
    /// Orders is how many order_completed events landed in the window.
    #[serde(rename = "orders", skip_serializing_if = "Option::is_none")]
    pub orders: Option<i32>,
    /// Reason says why the lens is unavailable. Omitted when it is available.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Revenue is the total those orders carried, in the events' own currency unit.
    #[serde(rename = "revenue", skip_serializing_if = "Option::is_none")]
    pub revenue: Option<f64>,
    /// Source is the warehouse table the lens read.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

impl CloudCommerceOverview {
    pub fn new() -> CloudCommerceOverview {
        CloudCommerceOverview {
            aov: None,
            available: None,
            orders: None,
            reason: None,
            revenue: None,
            source: None,
        }
    }
}

