/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudSampleIngest {
    #[serde(rename = "gpuModel", skip_serializing_if = "Option::is_none")]
    pub gpu_model: Option<String>,
    /// GPUUtil is accelerator utilization as a fraction 0..1; the warehouse clamps anything outside that.
    #[serde(rename = "gpuUtil", skip_serializing_if = "Option::is_none")]
    pub gpu_util: Option<f64>,
    /// GPUs is how many accelerators the reading covers, GPUModel the representative model name.
    #[serde(rename = "gpus", skip_serializing_if = "Option::is_none")]
    pub gpus: Option<i32>,
    /// Host is the node's hostname, for display.
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "memFree", skip_serializing_if = "Option::is_none")]
    pub mem_free: Option<i32>,
    /// MemUsed and MemFree are host memory in bytes.
    #[serde(rename = "memUsed", skip_serializing_if = "Option::is_none")]
    pub mem_used: Option<i32>,
    /// Unit is the reporting node's own id — the same id it registered under, and the key the board joins this series onto. Required.
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl CloudSampleIngest {
    pub fn new() -> CloudSampleIngest {
        CloudSampleIngest {
            gpu_model: None,
            gpu_util: None,
            gpus: None,
            host: None,
            mem_free: None,
            mem_used: None,
            unit: None,
        }
    }
}

