/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudTreasuryReport {
    /// lifetime revenue-share into the fund
    #[serde(rename = "accruedCents", skip_serializing_if = "Option::is_none")]
    pub accrued_cents: Option<i32>,
    /// program → lifetime paid
    #[serde(rename = "byProgramCents", skip_serializing_if = "Option::is_none")]
    pub by_program_cents: Option<std::collections::HashMap<String, i32>>,
    /// lifetime backed payouts out of the fund
    #[serde(rename = "paidCents", skip_serializing_if = "Option::is_none")]
    pub paid_cents: Option<i32>,
    /// current revenue-share policy
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<Box<models::CloudSharePolicy>>,
    /// fund:reserve balance (available now)
    #[serde(rename = "reserveCents", skip_serializing_if = "Option::is_none")]
    pub reserve_cents: Option<i32>,
    /// reserve > 0: at least some payout is backable
    #[serde(rename = "solventForPayout", skip_serializing_if = "Option::is_none")]
    pub solvent_for_payout: Option<bool>,
}

impl CloudTreasuryReport {
    pub fn new() -> CloudTreasuryReport {
        CloudTreasuryReport {
            accrued_cents: None,
            by_program_cents: None,
            paid_cents: None,
            policy: None,
            reserve_cents: None,
            solvent_for_payout: None,
        }
    }
}

