/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudSubjectSummary {
    /// CreatedAt is the unix second the subject was recorded.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i32>,
    /// HasEmail reports whether a contact email is on file, without exposing it.
    #[serde(rename = "hasEmail", skip_serializing_if = "Option::is_none")]
    pub has_email: Option<bool>,
    /// ID is the subject's opaque id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Kind is the party type: \"individual\" (KYC) or \"business\" (KYB).
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// Ref is the org's own opaque external id for this subject.
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
}

impl CloudSubjectSummary {
    pub fn new() -> CloudSubjectSummary {
        CloudSubjectSummary {
            created_at: None,
            has_email: None,
            id: None,
            kind: None,
            r#ref: None,
        }
    }
}

