/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudRedemption {
    /// Code is the promo redeemed.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// CreditCents is the discount value credited to the org's wallet — the promo is realized as a NON-CASH credit, not a subscription coupon.
    #[serde(rename = "creditCents", skip_serializing_if = "Option::is_none")]
    pub credit_cents: Option<i32>,
    /// CreditEntryID is the finance ledger entry that credit landed in.
    #[serde(rename = "creditEntryId", skip_serializing_if = "Option::is_none")]
    pub credit_entry_id: Option<String>,
    /// Plan and Seats are what was redeemed against.
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<String>,
    /// RedeemedAt is unix seconds.
    #[serde(rename = "redeemedAt", skip_serializing_if = "Option::is_none")]
    pub redeemed_at: Option<i32>,
    #[serde(rename = "seats", skip_serializing_if = "Option::is_none")]
    pub seats: Option<i32>,
}

impl CloudRedemption {
    pub fn new() -> CloudRedemption {
        CloudRedemption {
            code: None,
            credit_cents: None,
            credit_entry_id: None,
            plan: None,
            redeemed_at: None,
            seats: None,
        }
    }
}

