/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudPlanVocab {
    /// EngineFeatures are the inference-engine capabilities a license can grant: inference, embeddings, rerank, training, vision, audio, tools.
    #[serde(rename = "engine_features", skip_serializing_if = "Option::is_none")]
    pub engine_features: Option<Vec<String>>,
    /// Keys maps every entitlement key to its descriptor — key, namespace, JSON type(s), nullability, unit, enum and title, as the schema declares them.
    #[serde(rename = "keys", skip_serializing_if = "Option::is_none")]
    pub keys: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Namespaces are the entitlement key namespaces: the prefix before the dot in \"ai.tokens_per_min\".
    #[serde(rename = "namespaces", skip_serializing_if = "Option::is_none")]
    pub namespaces: Option<Vec<String>>,
}

impl CloudPlanVocab {
    pub fn new() -> CloudPlanVocab {
        CloudPlanVocab {
            engine_features: None,
            keys: None,
            namespaces: None,
        }
    }
}

