/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommerceCheckoutRequest {
    #[serde(rename = "cartId", skip_serializing_if = "Option::is_none")]
    pub cart_id: Option<String>,
    #[serde(rename = "buyer", skip_serializing_if = "Option::is_none")]
    pub buyer: Option<Box<models::CommerceBuyer>>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::CommerceLineItem>>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(rename = "shippingMethod", skip_serializing_if = "Option::is_none")]
    pub shipping_method: Option<String>,
    #[serde(rename = "couponCodes", skip_serializing_if = "Option::is_none")]
    pub coupon_codes: Option<Vec<String>>,
    #[serde(rename = "payment", skip_serializing_if = "Option::is_none")]
    pub payment: Option<Box<models::CommercePaymentRequest>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl CommerceCheckoutRequest {
    pub fn new() -> CommerceCheckoutRequest {
        CommerceCheckoutRequest {
            cart_id: None,
            buyer: None,
            items: None,
            currency: None,
            shipping_method: None,
            coupon_codes: None,
            payment: None,
            metadata: None,
        }
    }
}

