/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Company {
    /// ARR is annual recurring revenue in minor units (cents) of Currency.
    #[serde(rename = "arr", skip_serializing_if = "Option::is_none")]
    pub arr: Option<i32>,
    /// City is the head-office city.
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// Country is the head-office country.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// CreatedAt is the unix second the company was created. Server-owned.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i32>,
    /// Currency is the ISO code ARR is denominated in; a write that names none stores USD.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// DomainName is the company's primary domain, e.g. \"acme.com\".
    #[serde(rename = "domainName", skip_serializing_if = "Option::is_none")]
    pub domain_name: Option<String>,
    /// Employees is the headcount.
    #[serde(rename = "employees", skip_serializing_if = "Option::is_none")]
    pub employees: Option<i32>,
    /// ID is the server-minted company id (\"comp_\" + 128 random bits).
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// ICP marks the company as an ideal-customer-profile fit.
    #[serde(rename = "idealCustomerProfile", skip_serializing_if = "Option::is_none")]
    pub ideal_customer_profile: Option<bool>,
    /// Linkedin is the company's LinkedIn URL.
    #[serde(rename = "linkedinLink", skip_serializing_if = "Option::is_none")]
    pub linkedin_link: Option<String>,
    /// Name is the company name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// UpdatedAt is the unix second of the last write. Server-owned.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i32>,
    /// XLink is the company's X (Twitter) URL.
    #[serde(rename = "xLink", skip_serializing_if = "Option::is_none")]
    pub x_link: Option<String>,
}

impl Company {
    pub fn new() -> Company {
        Company {
            arr: None,
            city: None,
            country: None,
            created_at: None,
            currency: None,
            domain_name: None,
            employees: None,
            id: None,
            ideal_customer_profile: None,
            linkedin_link: None,
            name: None,
            updated_at: None,
            x_link: None,
        }
    }
}

