/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisconnectOut {
    /// Disconnected is always true — the org's secrets and connection row are gone.
    #[serde(rename = "disconnected", skip_serializing_if = "Option::is_none")]
    pub disconnected: Option<bool>,
}

impl DisconnectOut {
    pub fn new() -> DisconnectOut {
        DisconnectOut {
            disconnected: None,
        }
    }
}

