/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IamControllersPeriodLinkForm : Unlink a federated provider from a user (controllers.LinkForm).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IamControllersPeriodLinkForm {
    #[serde(rename = "providerType")]
    pub provider_type: String,
    #[serde(rename = "user")]
    pub user: Box<models::IamObjectPeriodUser>,
}

impl IamControllersPeriodLinkForm {
    /// Unlink a federated provider from a user (controllers.LinkForm).
    pub fn new(provider_type: String, user: models::IamObjectPeriodUser) -> IamControllersPeriodLinkForm {
        IamControllersPeriodLinkForm {
            provider_type,
            user: Box::new(user),
        }
    }
}

