/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MyReferrals {
    /// Code is the org's STABLE referral code — a deterministic function of the org id, so it never changes and never has to be stored to be reproduced.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Counts tallies this org's referrals by status.
    #[serde(rename = "counts", skip_serializing_if = "Option::is_none")]
    pub counts: Option<Box<models::StatusCounts>>,
    /// CreditsEarnedCents is the total promo credit this org has earned as the REFERRER, in USD cents.
    #[serde(rename = "creditsEarnedCents", skip_serializing_if = "Option::is_none")]
    pub credits_earned_cents: Option<i32>,
    /// Link is the shareable signup link carrying the code, on the brand's own host.
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    /// RefereeBonusCents is what a referee is granted on qualification, in USD cents.
    #[serde(rename = "refereeBonusCents", skip_serializing_if = "Option::is_none")]
    pub referee_bonus_cents: Option<i32>,
    /// Referrals is one row per org that signed up with this code.
    #[serde(rename = "referrals", skip_serializing_if = "Option::is_none")]
    pub referrals: Option<Vec<models::MyReferralView>>,
    /// ReferrerBonusCents is what the referrer is granted when a referee qualifies, in USD cents.
    #[serde(rename = "referrerBonusCents", skip_serializing_if = "Option::is_none")]
    pub referrer_bonus_cents: Option<i32>,
}

impl MyReferrals {
    pub fn new() -> MyReferrals {
        MyReferrals {
            code: None,
            counts: None,
            credits_earned_cents: None,
            link: None,
            referee_bonus_cents: None,
            referrals: None,
            referrer_bonus_cents: None,
        }
    }
}

