/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OraclesOut {
    /// Oracles is one row per on-chain price feed, or an empty list when the graph is unreachable or carries none — never a fabricated feed.
    #[serde(rename = "oracles", skip_serializing_if = "Option::is_none")]
    pub oracles: Option<Vec<models::OracleView>>,
}

impl OraclesOut {
    pub fn new() -> OraclesOut {
        OraclesOut {
            oracles: None,
        }
    }
}

