/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OverviewData {
    #[serde(rename = "activeProducts", skip_serializing_if = "Option::is_none")]
    pub active_products: Option<i32>,
    #[serde(rename = "creditsCents", skip_serializing_if = "Option::is_none")]
    pub credits_cents: Option<i32>,
    #[serde(rename = "drift", skip_serializing_if = "Option::is_none")]
    pub drift: Option<i32>,
    #[serde(rename = "lastSync", skip_serializing_if = "Option::is_none")]
    pub last_sync: Option<String>,
    #[serde(rename = "orgs", skip_serializing_if = "Option::is_none")]
    pub orgs: Option<i32>,
    #[serde(rename = "products", skip_serializing_if = "Option::is_none")]
    pub products: Option<i32>,
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<models::SourceStatus>>,
    #[serde(rename = "spendCents30d", skip_serializing_if = "Option::is_none")]
    pub spend_cents30d: Option<i32>,
    #[serde(rename = "tokens30d", skip_serializing_if = "Option::is_none")]
    pub tokens30d: Option<i32>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<i32>,
}

impl OverviewData {
    pub fn new() -> OverviewData {
        OverviewData {
            active_products: None,
            credits_cents: None,
            drift: None,
            last_sync: None,
            orgs: None,
            products: None,
            sources: None,
            spend_cents30d: None,
            tokens30d: None,
            users: None,
        }
    }
}

