/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PricingSubscriptionPlan {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "priceMonthly", skip_serializing_if = "Option::is_none")]
    pub price_monthly: Option<f64>,
    #[serde(rename = "priceAnnual", skip_serializing_if = "Option::is_none")]
    pub price_annual: Option<f64>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Category>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<String>>,
    #[serde(rename = "limits", skip_serializing_if = "Option::is_none")]
    pub limits: Option<Box<models::PricingSubscriptionPlanLimits>>,
    #[serde(rename = "payouts", skip_serializing_if = "Option::is_none")]
    pub payouts: Option<Box<models::PricingSubscriptionPlanPayouts>>,
}

impl PricingSubscriptionPlan {
    pub fn new() -> PricingSubscriptionPlan {
        PricingSubscriptionPlan {
            id: None,
            name: None,
            description: None,
            price_monthly: None,
            price_annual: None,
            category: None,
            features: None,
            limits: None,
            payouts: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Category {
    #[serde(rename = "personal")]
    Personal,
    #[serde(rename = "professional")]
    Professional,
    #[serde(rename = "business")]
    Business,
    #[serde(rename = "enterprise")]
    Enterprise,
}

impl Default for Category {
    fn default() -> Category {
        Self::Personal
    }
}

