/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectsSite : A live site in the org's list — a live project at its canonical live URL.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsSite {
    #[serde(rename = "slug")]
    pub slug: String,
    /// Canonical live URL, https://<slug>.<apex>.
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "name")]
    pub name: String,
    /// Always \"live\" in this list.
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
}

impl ProjectsSite {
    /// A live site in the org's list — a live project at its canonical live URL.
    pub fn new(slug: String, url: String, name: String, status: String, updated_at: i64) -> ProjectsSite {
        ProjectsSite {
            slug,
            url,
            name,
            status,
            updated_at,
        }
    }
}

