/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProvisioningCreateResponse : Returned on 201. `password` and `username` are present only for secretful kinds (sql, kv, and the dedicated datastore/docdb admin credential). The password is returned ONCE and is never retrievable again. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvisioningCreateResponse {
    /// Server-generated resource id.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "name")]
    pub name: String,
    /// Resource status (e.g. \"ready\", or \"provisioning\" for a dedicated instance still coming up).
    #[serde(rename = "status")]
    pub status: String,
    /// Customer-facing host (public gateway host, or dedicated instance service).
    #[serde(rename = "host")]
    pub host: String,
    #[serde(rename = "port")]
    pub port: i32,
    /// Present only for secretful kinds.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "database")]
    pub database: String,
    /// Public, routable DSN (internal admin host is remapped out).
    #[serde(rename = "connectionString")]
    pub connection_string: String,
    /// Present only for secretful kinds; returned ONCE.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl ProvisioningCreateResponse {
    /// Returned on 201. `password` and `username` are present only for secretful kinds (sql, kv, and the dedicated datastore/docdb admin credential). The password is returned ONCE and is never retrievable again. 
    pub fn new(id: String, kind: Kind, name: String, status: String, host: String, port: i32, database: String, connection_string: String) -> ProvisioningCreateResponse {
        ProvisioningCreateResponse {
            id,
            kind,
            name,
            status,
            host,
            port,
            username: None,
            database,
            connection_string,
            password: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "sql")]
    Sql,
    #[serde(rename = "vector")]
    Vector,
    #[serde(rename = "datastore")]
    Datastore,
    #[serde(rename = "kv")]
    Kv,
    #[serde(rename = "search")]
    Search,
    #[serde(rename = "s3")]
    S3,
    #[serde(rename = "docdb")]
    Docdb,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Sql
    }
}

