/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetentionGrid {
    #[serde(rename = "cohorts", skip_serializing_if = "Option::is_none")]
    pub cohorts: Option<Vec<models::RetentionCohort>>,
    /// \"month\"
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<String>,
    #[serde(rename = "periods", skip_serializing_if = "Option::is_none")]
    pub periods: Option<i32>,
}

impl RetentionGrid {
    pub fn new() -> RetentionGrid {
        RetentionGrid {
            cohorts: None,
            interval: None,
            periods: None,
        }
    }
}

