/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SampleIngest {
    #[serde(rename = "gpuModel", skip_serializing_if = "Option::is_none")]
    pub gpu_model: Option<String>,
    /// GPUUtil is accelerator utilization as a fraction 0..1; the warehouse clamps anything outside that.
    #[serde(rename = "gpuUtil", skip_serializing_if = "Option::is_none")]
    pub gpu_util: Option<f64>,
    /// GPUs is how many accelerators the reading covers, GPUModel the representative model name.
    #[serde(rename = "gpus", skip_serializing_if = "Option::is_none")]
    pub gpus: Option<i32>,
    /// Host is the node's hostname, for display.
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "memFree", skip_serializing_if = "Option::is_none")]
    pub mem_free: Option<i32>,
    /// MemUsed and MemFree are host memory in bytes.
    #[serde(rename = "memUsed", skip_serializing_if = "Option::is_none")]
    pub mem_used: Option<i32>,
    /// Unit is the reporting node's own id — the same id it registered under, and the key the board joins this series onto. Required.
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl SampleIngest {
    pub fn new() -> SampleIngest {
        SampleIngest {
            gpu_model: None,
            gpu_util: None,
            gpus: None,
            host: None,
            mem_free: None,
            mem_used: None,
            unit: None,
        }
    }
}

