/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusComponent {
    /// CurrentStatus is this component's own condition: \"full_outage\" for a service that did not answer its health probe at all.
    #[serde(rename = "current_status", skip_serializing_if = "Option::is_none")]
    pub current_status: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl StatusComponent {
    pub fn new() -> StatusComponent {
        StatusComponent {
            current_status: None,
            id: None,
            name: None,
        }
    }
}

