/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsSessions {
    /// ActiveSessions maps a workspace uuid to its connected sessions. It carries only the token's OWN workspace, and is empty for a token that names none.
    #[serde(rename = "activeSessions", skip_serializing_if = "Option::is_none")]
    pub active_sessions: Option<std::collections::HashMap<String, Vec<models::StatsUser>>>,
}

impl StatsSessions {
    pub fn new() -> StatsSessions {
        StatsSessions {
            active_sessions: None,
        }
    }
}

