/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Strategy {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    /// long-form explainer (nil for un-blogged tactics)
    #[serde(rename = "blog", skip_serializing_if = "Option::is_none")]
    pub blog: Option<Box<models::Blog>>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// modern | heritage
    #[serde(rename = "era", skip_serializing_if = "Option::is_none")]
    pub era: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// the spine slug this tactic files under
    #[serde(rename = "principle", skip_serializing_if = "Option::is_none")]
    pub principle: Option<String>,
    /// provenance / attribution
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "workload", skip_serializing_if = "Option::is_none")]
    pub workload: Option<String>,
}

impl Strategy {
    pub fn new() -> Strategy {
        Strategy {
            action: None,
            blog: None,
            category: None,
            enabled: None,
            era: None,
            id: None,
            principle: None,
            source: None,
            tags: None,
            workload: None,
        }
    }
}

