/*
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncTally {
    /// Live is the number of vouchers newly posted to the live ledger.
    #[serde(rename = "live", skip_serializing_if = "Option::is_none")]
    pub live: Option<i32>,
    /// Sandbox is the number newly posted to the sandbox ledger.
    #[serde(rename = "sandbox", skip_serializing_if = "Option::is_none")]
    pub sandbox: Option<i32>,
}

impl SyncTally {
    pub fn new() -> SyncTally {
        SyncTally {
            live: None,
            sandbox: None,
        }
    }
}

