/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 *
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VectorHnswConfig {
    #[serde(rename = "m", skip_serializing_if = "Option::is_none")]
    pub m: Option<i32>,
    #[serde(rename = "ef_construct", skip_serializing_if = "Option::is_none")]
    pub ef_construct: Option<i32>,
    #[serde(rename = "full_scan_threshold", skip_serializing_if = "Option::is_none")]
    pub full_scan_threshold: Option<i32>,
    #[serde(rename = "max_indexing_threads", skip_serializing_if = "Option::is_none")]
    pub max_indexing_threads: Option<i32>,
    #[serde(rename = "on_disk", skip_serializing_if = "Option::is_none")]
    pub on_disk: Option<bool>,
}

impl VectorHnswConfig {
    pub fn new() -> VectorHnswConfig {
        VectorHnswConfig {
            m: None,
            ef_construct: None,
            full_scan_threshold: None,
            max_indexing_threads: None,
            on_disk: None,
        }
    }
}

